# Generated by Django 4.0.4 on 2023-07-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_allcities_country_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcities',
            name='city_ru',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='allcities',
            name='country_ru',
            field=models.CharField(default='', max_length=100),
        ),
    ]
